\chapter{Granular measures of agricultural land-use influence lake nitrogen and phosphorus differently at macroscales}

# Abstract 

Agricultural land-use is typically associated with high stream nutrient concentrations and increased nutrient loading to lakes. For lakes, evidence for these associations mostly comes from studies on individual lakes or watersheds that relate concentrations of nitrogen (N) or phosphorus (P) to aggregate measures of agricultural land-use, such as the proportion of land used for agriculture in a lake’s watershed. However, at macroscales (i.e., in hundreds to thousands of lakes across large spatial extents), there is high variability around such relationships and it is unclear whether considering more granular (or detailed) agricultural data, such as fertilizer application, planting of specific crops, or the extent of near-stream cropping, would improve prediction and inform understanding of lake nutrient drivers. Furthermore, it is unclear whether lake N and P would have different relationships to such measures and whether these relationships would vary by region, since regional variation has been observed in prior studies using aggregate measures of agriculture. To address these knowledge gaps, we examined relationships between granular measures of agricultural activity and lake total phosphorus (TP) and total nitrogen (TN) concentrations in 928 lakes and their watersheds in the Northeastern and Midwest U.S. using a Bayesian hierarchical modelling approach. We found that both lake TN and TP concentrations were related to these measures of agriculture, especially near-stream agriculture. The relationships between measures of agriculture and lake TN concentrations were more regionally variable than those for TP. Conversely, TP concentrations were more strongly related to lake-specific measures like depth and watershed hydrology relative to TN. Our finding that lake TN and TP concentrations have different relationships with granular measures of agricultural activity has implications for the design of effective and efficient policy approaches to maintain and improve water quality.
