\chapter{Bathymetry data from thousands of lakes show that lake depth prediction is confounded by difficulty modeling inlake slope}

# Abstract 

Measured depth data is only available for a small fraction of all lakes. As a result, our ability to understand and predict important depth-dependent processes for all lakes is limited. Lake depth prediction studies to date have generally taken one of two approaches 1) a statistical approach relating depth to map-derived predictors like lake area or 2) a geometric approach where depth is calculated analytically (e.g. using trigonometry) after fitting lakes to some geometric shape based on survey-derived predictors like lake volume. While there is some evidence to suggest that a geometric approach produces more accurate depth estimates, the data requirements of such models mostly preclude out-of-sample depth prediction. As an alternative, we investigated the possibility that map-derived parameters could serve as proxies for the more difficult to obtain survey-derived parameters required by geometric models. To this end, we developed a simple geometric model of lakes with two survey-derived (i.e. calculated from bathymetry) parameters, a horizontal measure (deepest point distance) and a vertical measure (inlake slope) each having a corresponding map-derived proxy (visual center distance and nearshore slope respectively). We constructed random forest models on approximately 5,000 lakes in 9 U.S. States where we fit calculated (i.e. “true”) maximum depth as a function of analytically derived maximum depth using different combinations of map-derived proxies. Our models included a variety of additional map-derived parameters such as lake area and perimeter to account for the possibility that other non-proxy metrics might be related to depth. We found that depth prediction errors were at their lowest when models included a true slope measure (inlake slope) whereas we observed little benefit to having a true distance measure (deepest point location). Furthermore, we observed that predictions from models lacking a true slope covariate systematically overpredicted lake depth in concave (i.e. bowl-shaped lakes) and reservoir lakes. Our results suggest that global estimates of lake depth are likely overestimated.
