# Conclusion {-}

## Research Frontiers {-}
\noindent
Each of the preceding chapters left some analyses unexplored that represent emerging research frontiers in macroscale lake research. For instance, In Chapter 1 I used lake connectivity metrics to quantify the effect of connectivity among lakes and streams as well as connectivity of lakes and their terrestrial watersheds on lake P retention. However, “connectivity” is a somewhat nebulous idea that is difficult to quantify with specific metrics. For instance, I found that not all metrics can be mapped onto a “high connectivity” versus “low connectivity” gradient. A potential alternative to this messy mapping of connectivity onto discrete metrics is to compare the drainage pattern of a given stream network against an optimal drainage pattern which has the highest possible connectivity for a given watershed. A recent tool, the OCNet R package, may facilitate exactly such calculations as it can calculate the optimal distributions of upstream and downstream lengths, contributing area, and the space-filling attributes of specific watersheds (Carraro et al. 2020). 

In Chapter 2, I examined relationships between lake nutrient concentrations and measures of agricultural activity quantified at varying levels of spatial and process-level detail. This effort was limited in the types of agricultural measures that were considered owing to the spatial extent of the study, challenges in data integration of diverse data types, and complicated model interpretation and building. For instance, it would have been great to have included other aspects of agriculture like animal feeding operations. Unfortunately, the limited spatial resolution 
of this data (only to county level) made it difficult to integrate with crop and nutrient input data. In addition, I was unable to explore temporal variation in lake nutrient-agriculture relationships which may have contributed to overall model uncertainty. Unfortunately, few lakes have adequate nutrient concentration time series data to drive such a model. Furthermore, assembly of agricultural covariates through time is a significant challenge. 

In Chapter 3, I tested the assumptions of geometric models of lake depth using bathymetry data. I show that such models are highly sensitive to imperfect proxies of lake slope. Even with measures of true slope derived from bathymetry, model prediction accuracy is still barely accurate enough to distinguish between “shallow” and non-shallow lakes. A fruitful area of future research would be to test different modeling techniques such as ordinal modeling (i.e. shallow versus not shallow) and new topobathymetric data products that integrate topographic and bathymetric data into a single product. This may boost predictive power and avoid changes in resolution and changes in scale that likely introduce uncertainty in model predictions.

## Future Directions {-}
\noindent
I developed each of the preceding chapters using a landscape limnology and macrosystems ecology approach. Throughout this process I noticed several commonalities amongst each dissertation chapter. One commonality was simply the large number of modeling choices that underpin each result. My hope is that the most important of these choices is reflected in the text and the remaining ones are sufficiently documented in the code supplements accompanying each chapter. In some cases, I was fortunate to have the opportunity to explore the sensitivity of my model results to each choice. However, the sheer number of these choices made it intractable to test them all. Choices such as what type of regionalization to use or how and when to aggregate data from one spatial scale to another were not always straightforward. Future exploration of these choices would likely go a long way in strengthening our understanding of spatial patterning of lake characteristics at macroscales and generating exciting new research questions.

A second commonality I found was that models incorporating spatial variation are very often superior in terms of predictive performance and model fit relative to non-spatial models. However, I only really interrogated one level of spatial variation, which was variation within and among hydrologic subbasins. The question of why two neighboring lakes might differ in terms of trophic status despite having nearly identical land-use, nutrient loading, morphometry, and climate remains largely unresolved by my analyses. Answering this question may require the application of new techniques such as those that consider spatial autocorrelation within stream networks or new data types derived from the output of fine-scale hydrologic models. Exploring these is likely to be critical for resolving the types of local-scale spatial variation which is so important for the management of freshwater ecosystems.

