--- 
title: "Spatial patterning of lake nutrients and morphometry at macroscales: importance of regional factors and aquatic-terrestrial linkages"
author: "Joseph Stachelek"
date: "2020"
site: bookdown::bookdown_site
output: bookdown::pdf_book
documentclass: msu-thesis
bibliography: [dissertation.bib]
biblio-style: plainnat
link-citations: yes
github-repo: jsta/dissertation
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---

# Abstract {-}

Lakes are classically viewed as discrete ecosystems bounded on all sides by land. However, a narrow focus on lakes as discrete units is incompatible with the scale of many management programs and ignores the placement of lakes relative to their larger ecological context. While it is clear that lakes are not isolated units but are instead embedded components of lake-river networks and have a broader landscape (i.e. regional) context, it is not always clear how this embedding is borne out quantitatively. For example, is the position of a lake in a multi-lake network a dominant predictor of nutrient retention? Or, how strongly does the arrangement of streams and near-stream land-use (i.e. aquatic-terrestrial linkages) affect lake nutrient concentrations? To date, we have been unable to quantitatively address these questions in a data-driven manner because the necessary data has not previously been available for many lakes over large geographic extents (i.e. the macroscale). As a result, prior research has mostly been conducted on single lakes or in some cases groups of nearby lakes in a single region. In the following chapters, I developed several macroscale lake databases to examine hundreds to thousands of lakes across diverse local and regional settings. I used these databases to investigate the roles of both local and regional processes and aquatic-terrestrial linkages in determining lake nutrient retention, nutrient concentrations, and basic lake morphometry.

In my first chapter, I show that throughout Northeastern and Midwest US, lakes with higher connectivity have lower nutrient retention but this “connectivity effect” is apparent at the scale of entire lake networks rather than more localized lake subwatersheds. My findings suggest that a broader whole-network perspective is likely to be more effective than a narrow lake-specific perspective for regulatory frameworks focused on eutrophication.
In my second chapter, I show that lake nutrient concentrations are related to a variety of agricultural activity measures beyond the percent of the watershed in agricultural land use. I show that when one measure in particular, the percentage of agricultural land use in near-stream areas, is elevated; this signals a high likelihood of elevated lake nutrient concentrations. I further show that lake total phosphorus concentrations have different relationships with measures of agricultural activity relative to lake total nitrogen concentrations. My findings suggest that differences in lake nutrient sensitivity to agricultural activity may affect the outcome of policies to enhance water quality depending on whether they focus on lake N or P.
In my third and final chapter, I test the utility of geometric models for predicting lake depth for all lakes. I show that one of the assumptions of such models, that slope proxies are representative of true inlake slope, is not supported by bathymetry data from 5,000 lakes. This non-representativeness has implications for predictive accuracy and model bias in lakes of different types or shapes. My findings suggest that geometric models overestimate the depth of  lakes with concave cross-section shapes and those classified as reservoirs.

# Acknowledgements {-}

It’s cliche to say you’ve stood on the shoulders of giants but maybe it’s just this type of elevated perspective that’s needed to see how the pieces fit together - to see how lakes are related to each other - and to see how lakes are related to their ecological context. The shoulders I’ve stood on include of course my advisor, Pat Soranno, as well as the other members of our lab Kendra Cheruvelil, Katelyn King, Ian McCullough, Autumn Poisson, Nick Skaff, and Nicole Smith whose support has been much appreciated. I would also like to thank my committee members Drs Elise Zipkin and Dana Infante who provided excellent advice and direction on this Dissertation journey. As a group, I would like to thank the members of the Continental Limnology and CNH Lakes Projects whose diversity of perspectives provided much needed context for my research. Also, thank you to everyone from the numerous federal, state, tribal, and non-profit agencies, as well as university researchers and citizen scientist data collectors and curators whose data unpin my research. Finally, I would like to thank Sheena Stachelek and the rest of my family for their love and encouragement.

\vspace{2em}
\noindent
“You can’t stop water. Water will find a way.” \\
- Colin Saunders
